import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import { useState } from "react";
import {AiFillGithub, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai';
import Image from 'next/image';
import georgedev from '../public/favicon.png';
import web1 from '../public/alexasmusicproduction.png';
import web2 from '../public/nucampdemo.png';
import web3 from '../public/ordering-app.png';
import web4 from '../public/to-do-list.png';
import web5 from '../public/guess-my-number.png';
import web6 from '../public/modals.png';
import web7 from '../public/pig-game.png';
import css from '../public/css.png'
import github from '../public/github.png'
import html from '../public/html.png'
import javascript from '../public/javascript.png'
import next from '../public/nextjs.png'
import node from '../public/node.png'
import react from '../public/react.png'
import tailwind from '../public/tailwind.png'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false); 

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>George Saint Hilaire SWE | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section>
          <div>
            <nav className='py-10 flex justify-between '>
              <h1 className='text-xl font-burtons  dark:text-white'>George Saint Hilaire SWE</h1>
              <ul className='flex items-center'>
              <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:bg-white rounded-lg p-1"
                />
                <li><a className="bg-gradient-to-r from-blue-500 to-teal-500 text-white px-4 py-2 rounded ml-8" href="George.Saint.Hilaire.Resume_Dec2022 (1).pdf">Resume</a></li>
              </ul>
            </nav>
          </div>
          <div className=" bg-gray-200 shadow-xl rounded-2xl p-5 dark:bg-gray-700 ">
                  <div className="text-center p-10 py-10">
                    <h2 className="text-5xl py-2 text-purple-600 font-medium dark:text-white md:text-6xl">
                      George Saint Hilaire
                    </h2>
                    <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
                      Software Engineer 
                    </h3>
                    <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                    Hi! My name is George, I’m a junior software engineer based in NYC. Check out my portfolio below!                     </p>
                    <div className="mx-auto bg-gradient-to-b from-purple-500 to-teal-500 rounded-full w-auto h-auto relative overflow-hidden mt-20 md:h-96 md:w-96">
                      <Image src={georgedev} alt='' />
                    </div>
                    <div className="text-5xl pt-12 flex justify-center gap-16 py-3 text-black-600 dark:text-gray-400">
                      <a href="https://www.instagram.com/g_saint97/"><AiFillInstagram /></a>
                      <a href="https://www.linkedin.com/in/george-saint-hilaire-303820191/"><AiFillLinkedin /></a>
                      <a href="https://github.com/g-saint97"><AiFillGithub /></a>
                    </div>
                  </div>
            </div>
        </section>

        <section>
          <div className='text-center py-12'>
            <h3 className="text-4xl py-1 dark:text-white underline underline-offset-1">About Me</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200">
            As is the case with so many people out there, the beginning of the pandemic and the shut down of the world opened up a unique opportunity for me to change careers. Stuck at home, I began to make a shift from a career as a NYC buildings employee in business school, to a software engineer.
            </p>
            <p className="text-lg  py-5 leading-8 text-gray-800 dark:text-gray-200">
            Since then, I’ve read hundreds of documents, watched countless hours of YouTube tutorials, enrolled (and graduated!) from a full stack bootcamp, and began classes to resume and complete my Bachelor’s degree in Computer Science. 
            </p>
            <p className="text-lg  py-5 leading-8 text-gray-800 dark:text-gray-200">
            Now, I’m ready to enter the workforce! See below for examples of my work. I’m so excited to join your team!
            </p>
          </div>
          <h3 className="text-center text-4xl py-10 dark:text-white underline underline-offset-1 ">My experience</h3>
          <div className='flex justify-center'>
            <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-8 p-12 sm:px-0 ">
                <div className="basis-1/2 flex-1 p-12">
                <Image
                    className="rounded-md duration-200  hover:scale-105 m-5" width="150"
                    alt="images"
                    src={css}
                  />
                </div>
                <div className="basis-1/2 flex-1 p-12">
                  
                    <Image
                    className="rounded-lg duration-200  hover:scale-105 m-5" width="150"
                    alt="images"
                    src={html}
                  />
                </div>
                <div className="basis-1/2 flex-1 p-12">
                  
                  <Image
                    className="rounded-lg duration-200  hover:scale-105 m-5" width="150"
                    alt="images"
                    src={javascript}
                  />
                </div>
                <div className="basis-1/2 flex-1 p-12">
                  
                  <Image
                    className="rounded-lg duration-200  hover:scale-105 m-5" width="150"
                    alt="images"
                    src={react}
                  />
                </div>
                <div className="basis-1/2 flex-1 p-12">

                  <Image
                    className="rounded-lg duration-200  hover:scale-105 m-5" width="150"
                    alt="images"
                    src={github}
                  />
                </div>
                <div className="basis-1/2 flex-1 p-12">
                  <Image
                    className="rounded-lg duration-200  hover:scale-105 m-5" width="150"
                    alt="images"
                    src={tailwind}
                  />
                </div>
                <div className="basis-1/2 flex-1 p-12">
                  <Image
                    className="rounded-lg duration-200  hover:scale-105 m-5" width="150"
                    alt="images"
                    src={node}
                  />
                </div>
                <div className="basis-1/2 flex-1 p-12">
                  <Image
                    className="rounded-lg duration-200  hover:scale-105 m-5" width="150"
                    alt="images"
                    src={next}
                  />
                </div>
            </div>
          </div>
        </section>
            
        <section className="py-10 ">
          <div className='text-center py-12'>
            <h3 className="text-4xl py-1 dark:text-white underline underline-offset-1">Portofolio</h3>
            <p className="text-md p-5 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance, designer and
              developer, I've done remote volunteer work. One of them for an <span className="text-teal-500">Animal rescue </span>
              and collaborated with alanding site for customer to see what they do.
            </p>
            <p className="text-md p-5 leading-8 text-gray-800 dark:text-gray-200">
              Here I showcase a wide range of services, and personal projects.
            </p>
            <p className='text-lx font-bold underline underline-offset-1'>Check out my project</p>
          </div>
          <div className="flex flex-col p-5 gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
             <a href="https://www.alexasmusicproduction.com/"> 
             <Image
                className="rounded-lg duration-200 shadow-lg hover:scale-105"
                alt="images"
                src={web1}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://nucamp-website-demo.vercel.app/">
                <Image
                className="rounded-lg duration-200 shadow-lg hover:scale-105"
                alt="images"
                src={web2}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://drink-ordering-app.vercel.app/">
              <Image
                className="rounded-lg duration-200 shadow-lg hover:scale-105"
                alt="images"
                src={web3}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://task-tracker-project-react.vercel.app/">
              <Image
                className="rounded-lg duration-200 shadow-lg hover:scale-105"
                alt="images"
                src={web4}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://guess-my-number-game-alpha.vercel.app/">
              <Image
                className="rounded-lg duration-200 shadow-lg hover:scale-105"
                alt="images"
                src={web5}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://modal-ecru.vercel.app/">
              <Image
                className="rounded-lg duration-200 shadow-lg hover:scale-105"
                alt="images"
                src={web6}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://pig-game-silk-eta.vercel.app/">
              <Image
                className="rounded-lg duration-200 shadow-lg hover:scale-105"
                alt="images"
                src={web7}
              />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}