import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import { useState } from "react";
import {AiFillGithub, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai';
import Image from 'next/image';
import georgedev from '../public/favicon.png';
import design from '../public/front-end.png';
import code from '../public/back-end.png';
import consulting from '../public/mobile-dev.png';
import web1 from '../public/alexasmusicproduction.png';
import web2 from '../public/nucampdemo.png';
import web3 from '../public/ordering-app.png';
import web4 from '../public/to-do-list.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false); 

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>George Saint Hilaire SWE | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section>
          <div>
            <nav className='py-10 flex justify-between '>
              <h1 className='text-xl font-burtons  dark:text-white'>George Saint Hilaire SWE</h1>
              <ul className='flex items-center'>
              <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:bg-white rounded-lg p-1"
                />
                <li><a className="bg-gradient-to-r from-blue-500 to-teal-500 text-white px-4 py-2 rounded ml-8" href="George.Saint.Hilaire.Resume.docx">Resume</a></li>
              </ul>
            </nav>
          </div>
          <div className=" bg-gray-200 shadow-xl rounded-2xl p-5 dark:bg-gray-700 ">
                  <div className="text-center p-10 py-10">
                    <h2 className="text-5xl py-2 text-purple-600 font-medium dark:text-white md:text-6xl">
                      George Saint Hilaire
                    </h2>
                    <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
                      Software Engineer 
                    </h3>
                    <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                    Hi! My name is George, I’m a junior software engineer based in NYC. Check out my portfolio below!                     </p>
                    <div className="mx-auto bg-gradient-to-b from-purple-500 to-teal-500 rounded-full w-auto h-auto relative overflow-hidden mt-20 md:h-96 md:w-96">
                      <Image src={georgedev} alt='' />
                    </div>
                    <div className="text-5xl pt-12 flex justify-center gap-16 py-3 text-black-600 dark:text-gray-400">
                      <a href="https://www.instagram.com/g_saint97/"><AiFillInstagram /></a>
                      <a href="https://www.linkedin.com/in/george-saint-hilaire-303820191/"><AiFillLinkedin /></a>
                      <a href="https://github.com/g-saint97"><AiFillGithub /></a>
                    </div>
                  </div>
            </div>
        </section>

        <section>
          <div className='text-center py-12'>
            <h3 className="text-3xl py-1 dark:text-white ">About Me</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200">
            As is the case with so many people out there, the beginning of the pandemic and the shut down of the world opened up a unique opportunity for me to change careers. Stuck at home, I began to make a shift from a career as a NYC buildings employee in business school, to a software engineer.
            </p>
            <p className="text-lg  py-5 leading-8 text-gray-800 dark:text-gray-200">
            Since then, I’ve read hundreds of documents, watched countless hours of YouTube tutorials, enrolled (and graduated!) from a full stack bootcamp, and began classes to resume and complete my Bachelor’s degree in Computer Science. 
            </p>
            <p className="text-lg  py-5 leading-8 text-gray-800 dark:text-gray-200">
            Now, I’m ready to enter the workforce! See below for examples of my work. I’m so excited to join your team!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-xl p-10 rounded-xl my-10 bg-teal-500 dark:bg-gray-700 flex-1">
              <Image src={design} alt="images"
               width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Frond End
              </h3>
              <p className="py-2 dark:text-white">
                
              </p>
              <h4 className="py-4 font-bold text-black-600 dark:text-white">Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-white">HTML</p>
              <p className="text-gray-800 py-1 dark:text-white">CSS</p>
              <p className="text-gray-800 py-1 dark:text-white">JavaScript</p>
              <p className="text-gray-800 py-1 dark:text-white">Bootstrap</p>
              <p className="text-gray-800 py-1 dark:text-white">React</p>
              <p className="text-gray-800 py-1 dark:text-white">Next</p>
              <p className="text-gray-800 py-1 dark:text-white">TailWind</p>
            </div>
            <div className="text-center shadow-xl p-10 rounded-xl my-10 bg-blue-500 dark:bg-gray-700 flex-1">
              <Image src={code}  alt="images"
              width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Back-End
              </h3>
              <p className="py-2 dark:text-white">
          
              </p>
              <h4 className="py-4 font-bold text-black-600 dark:text-white">Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-white">Node Js</p>
              <p className="text-gray-800 py-1 dark:text-white">Express</p>
              <p className="text-gray-800 py-1 dark:text-white">MongoDB</p>
              <p className="text-gray-800 py-1 dark:text-white">MySQL</p>
            </div>
            <div className="text-center shadow-xl p-10 rounded-xl my-10 bg-purple-500 dark:bg-gray-700 flex-1">
              <Image src={consulting} alt="images"
               width={60} height={90} className="align-content: center"/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Mobile</h3>
              <p className="py-2 dark:text-white">
                
              </p>
              <h4 className="py-4 font-bold text-black-600 dark:text-white">Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-white">React Native</p>
              <p className="text-gray-800 py-1 dark:text-white">Android Studio</p>
            </div>
          </div>
        </section>
        <section className="py-10 ">
          <div className='text-center py-12'>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md p-5 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md p-5 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col p-5 gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
             <a href="https://www.alexasmusicproduction.com/"> 
             <Image
                className="rounded-lg object-cover shadow-lg hover:animate-bounce"
                alt="images"
                src={web1}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://nucamp-website-demo.vercel.app/">
                <Image
                className="rounded-lg object-cover shadow-lg hover:animate-bounce"
                alt="images"
                src={web2}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://drink-ordering-app.vercel.app/">
              <Image
                className="rounded-lg object-cover shadow-lg hover:animate-bounce"
                alt="images"
                src={web3}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://task-tracker-project-react.vercel.app/">
              <Image
                className="rounded-lg object-cover shadow-lg hover:animate-bounce"
                alt="images"
                src={web4}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="#">
              <Image
                className="rounded-lg object-cover shadow-lg hover:animate-bounce"
                alt="images"
                src={web5}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="#">
              <Image
                className="rounded-lg object-cover shadow-lg hover:animate-bounce"
                alt="images"
                src={web6}
              />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
